### ISSUE TITLE
Projects fail to build because of yanked git-cop

### ISSUE THREAD

**Issue by wintersolutions** [bkuhlmann/git-lint#3]
## Overview
```
Fetching gem metadata from https://rubygems.org/.........
Could not find git-cop-3.5.3 in any of the sources
```
In around 20 of our projects. 

You can do whatever you like with your projects, even renaming them for some political reasons that apply to your small part of the world. But yanking old versions that people rely on? Zero sympathy. You force people to update to ruby 2.7 or even 3.0, versions which still have many issues.

## Steps to Recreate
Use any version of `git-cop` < 4

## Desired Behavior
Legacy gems people are relying on are not being yanked for arbitrary reasons.

## Environment
```Linux x220 5.4.85-1-MANJARO #1 SMP PREEMPT Mon Dec 21 21:38:53 UTC 2020 x86_64 GNU/Linux```

**Comment by bkuhlmann** [comment]
Hey @wintersolutions :wave: Actually, I have a ton of sympathy and is why I updated all documentation _half a year ago_ to give people plenty of time for the transition. Here's a screenshot from the Git Cop project:

<img width="894" alt="Firefox-Git Cop-rc1dMc4k" src="https://user-images.githubusercontent.com/50245/103446971-923dac80-4c42-11eb-9386-2ee1c8d2a194.png">

Here's the Git log of when that update was made along with the corresponding _4.2.1_ version with the gem's post install message:

<img width="836" alt="iTerm2-git-cop-mfc73UCt" src="https://user-images.githubusercontent.com/50245/103446959-67ebef00-4c42-11eb-8b61-9395efd0764e.png">

...and here's the corresponding update to the `git-cop.gemspec`:

![image](https://user-images.githubusercontent.com/50245/103446854-99b08600-4c41-11eb-8958-d05d7b7690d0.png)

I've attached the source code in case it is of help:

[git-cop.zip](https://github.com/bkuhlmann/git-lint/files/5759498/git-cop.zip)

With that, you'd be able to compile and build an internal version until you can migrate over to [Git Lint](https://www.alchemists.io/projects/git-lint). :tada:

I'm going to close this issue as there isn't anything further I can do to help except strongly encourage migrating over to Git Lint when you can as all current development and support is happening there.

**Comment by wintersolutions** [comment]
Thanks for providing the code. I think you shouldn't have yanked the package since there is nothing wrong with it. Its your package you do as you please.

**Comment by bkuhlmann** [comment]
:bow: @wintersolutions True...but in order to be a good RubyGems citizen it's helpful to clean up the namespace so others can claim it if desired for a different purpose in the future. :wink: I've had to track down hard to reach developers, myself, and had a very hard time getting a hold of the original developer.
