### ISSUE TITLE
Version 1.4 doesn't support repositories without master branch

### ISSUE THREAD

**Issue by melg8** [bkuhlmann/git-lint#5]
## Overview
When using git-lint with version 1.4 (and maybe on later versions as well),
or repositories without branch called "master", and with default branch, for example, called "main".
git-lint failing with message:
``` bash
Git Lint: Invalid commit SHA: "fatal: ambiguous argument 'master..feature/TestBranch': unknown revision or path not in the working tree.". Unable to obtain commit details.
```

## Steps to Recreate
- install git-lint from rubygems.org with 1.4 version
- change directory to git project without "master" branch
- run "git-lint -a"

## Desired Behavior
Run checks without error, or to have config option to set default branch with different name (did i miss one?).

## Environment
NixOS 20.09, you can reliably reproduce my environment by using code from my repo:
https://github.com/melg8/cit/tree/feature/NixosBuild/ci/nix/git_lint
for that you need nix package manager and use nix-shell from nix directory:
``` bash
   nix-shell -E "with import <nixpkgs> {}; let git-lint = callPackage ./ci/nix/git_lint/default.nix {}; in mkShell { buildInputs = [ git-lint ];}"   
```

## Hotfix
I've managed to fix that behaviour by manually replacing "master" with "main" in following files:
- git-lint-1.4.0/lib/git/kit/repo.rb
- git-lint-1.4.0/lib/git/lint/branches/environments/local.rb
But that's seems to be adhoc solution.

## Thoughts
I'm working on project bringing ready to use linting solution for c++ developers, using nix and docker, but haven't used more recent versions of your tool, due to lack of support for ruby 3.0 in nixpkgs, but i suspect, that later versions can have same issue, due to similarities in code base:
https://github.com/bkuhlmann/git-lint/blob/bc416fcca6e7af0bdce4fc7919e79684d19124f6/lib/git/lint/branches/environments/local.rb#L18

Anyway, thanks for your work on this project.

Regards, Melg Eight.

**Comment by bkuhlmann** [comment]
:bow: **Meig**. Thanks for reporting this. I agree, this is a bug. Git Lint needs to respect your Git config [default branch](https://github.com/bkuhlmann/dotfiles/blob/main/home_files/.gitconfig.tt#L79-L80) but doesn't at the moment. I'll work on a fix for that next but won't be able to backport to 1.x.x, unfortunately. The fix would have to be for 2.x.x which supports Ruby 3.0.0. That said, your hotfix solution isn't a bad idea as it would allow you to build a custom version of Git Lint that would work for that scenario and buy you some time until you could acquire Ruby 3.0.0 support.
